# Build wheels and publish them to PyPi (for the master branch)
name: Python Wheels

on:
  workflow_dispatch:
  push:
    branches:
     - dev
  pull_request:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        name: PhotoshopAPI_Py
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-14, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    # We need to specify Xcode15.1 here as the default for macos-14 runners is 15.01 which has a bug 
    # causing linking to fail.
    - name: Setup Xcode 15.1
      if: matrix.os == 'macos-14'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'

    - uses: pypa/cibuildwheel@v2.16
      env:
        CC: gcc-13
        CXX: g++-13
        CIBW_ARCHS: auto64
        CIBW_SKIP: "*-musllinux_* pp*" #disable musllinux and pypy builds for now to speed up execution
        # We "Test" the python executable by running all our example files, this would be done a little better in the future
        CIBW_BEFORE_TEST: >
            ls -d PhotoshopExamples
        CIBW_TEST_COMMAND: >
            python -u {project}/PhotoshopExamples/tmp.py
            python -u {project}/PhotoshopExamples/AddLayerMasks/add_layer_masks.py &&
            python -u {project}/PhotoshopExamples/CreateGroups/create_groups.py &&
            python -u {project}/PhotoshopExamples/CreateSimpleDocument/create_simple_document.py &&
            python -u {project}/PhotoshopExamples/ExtractImageData/extract_image_data.py &&
            python -u {project}/PhotoshopExamples/ModifyLayerStructure/modify_layer_structure.py

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: PhotoshopAPI_Py
        path: wheelhouse/*.whl


  pypi-publish:
    name: Upload release to PyPI
    permissions:
      id-token: write
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: PhotoshopAPI_Py
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1